import { Actor } from 'apify';
import { createClient } from '@supabase/supabase-js';
import { load, type CheerioAPI } from 'cheerio';

const BASE='https://www.daraz.com.np';
const PRODUCT_SITEMAP=`${BASE}/sitemap-product-all.xml`;
const DARAZ_MARKETPLACE_ID='6a4f8822-e1bc-4e8b-be61-4d1a400f3c13';
const SUPABASE_URL=process.env.SUPABASE_URL||'https://foupthwcnnskqlzhoyep.supabase.co';
const SUPABASE_SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const CATEGORIES:Record<string,string>={smartphone:'smartphone',tablet:'tablet',laptop:'laptop','desktop computer':'desktop computer',printer:'printer',camera:'camera','smart tv':'smart tv','computer monitor':'computer monitor',refrigerator:'refrigerator','washing machine':'washing machine','air conditioner':'air conditioner',dishwasher:'dishwasher'};
type SearchProduct={title:string;url:string;itemId:string;price:number;originalPrice?:number;discount?:number;image?:string};
type Product=SearchProduct&{seller?:string;brand?:string;rating?:number;reviewCount?:number;specifications:Record<string,string>};
function clean(v:unknown){return String(v??'').replace(/\s+/g,' ').trim();}
function price(v:unknown):number|undefined{const m=String(v??'').replace(/,/g,'').match(/\d+(?:\.\d+)?/);if(!m)return;const n=Number(m[0]);return Number.isFinite(n)?n:undefined;}
function parsePriceText(v:unknown){const m=clean(v).match(/(?:Rs\.?|NPR)\s*[\d,]+(?:\.\d+)?/i);return m?price(m[0]):price(v);}
function normalizeUrl(v:string){try{const u=new URL(v,BASE);return `${u.origin}${u.pathname}`;}catch{return v;}}
function itemId(url:string){return url.match(/\/i(\d+)(?:-s\d+)?\.html/i)?.[1]||url;}
function isProductUrl(url:string){return /\/i\d+(?:-s\d+)?\.html(?:$|[?#])/i.test(url);}
function blocked(text:string){const $=load(text);const t=`${clean($('title').text())} ${clean($('body').text())}`.toLowerCase();return ['verify you are human','are you a robot','unusual traffic','access denied','robot check','please complete the captcha','captcha verification failed','security check required'].some(x=>t.includes(x));}
async function httpGet(url:string,timeoutMs=30000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9','Cache-Control':'no-cache'}});return{status:r.status,contentType:r.headers.get('content-type')||'',html:await r.text()};}finally{clearTimeout(timer);}}
function xmlLocs(text:string){return [...text.matchAll(/<loc(?:\s[^>]*)?>\s*([\s\S]*?)\s*<\/loc>/gi)].map(m=>m[1].replace(/^<!\[CDATA\[/i,'').replace(/\]\]>$/,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#x2F;/gi,'/').trim()).filter(Boolean);}
function addSpec(s:Record<string,string>,k:unknown,v:unknown){const key=clean(k),val=clean(v);if(!key||!val||key.length>150||val.length>2000)return;if(!s[key])s[key]=val;}
function tableSpecs($:CheerioAPI,s:Record<string,string>){$('table tr').each((_,r)=>{const c=$(r).find('th,td').map((_,e)=>clean($(e).text())).get().filter(Boolean);if(c.length>=2)addSpec(s,c[0],c.slice(1).join(' | '));});}
function labeledSpecs($:CheerioAPI,s:Record<string,string>){$('[class*="specification" i],[class*="specs" i],[class*="attribute" i],[class*="product-property" i]').each((_,b)=>{$(b).find('li,tr,p,div').each((_,r)=>{const c=$(r).children().map((_,e)=>clean($(e).text())).get().filter(Boolean);if(c.length>=2){addSpec(s,c[0],c.slice(1).join(' | '));return;}const t=clean($(r).text()),i=t.indexOf(':');if(i>1&&i<150)addSpec(s,t.slice(0,i),t.slice(i+1));});});}
function colonSpecs($:CheerioAPI,s:Record<string,string>){$('li,p,dt,dd').each((_,e)=>{const t=clean($(e).text()),i=t.indexOf(':');if(t.length>=3&&t.length<=600&&i>1&&i<120)addSpec(s,t.slice(0,i),t.slice(i+1));});}
function flatten(v:unknown,s:Record<string,string>,d=0){if(d>8||v==null)return;if(Array.isArray(v)){for(const x of v)flatten(x,s,d+1);return;}if(typeof v!=='object')return;for(const[k,x]of Object.entries(v as Record<string,unknown>)){const n=k.toLowerCase().replace(/[^a-z0-9]/g,'');if(['specifications','specification','attributes','attribute','productattributes','productspecifications','properties'].includes(n)){flatten(x,s,d+1);continue;}if(['string','number','boolean'].includes(typeof x)){if(d>=1)addSpec(s,k,x);}else if(d<5)flatten(x,s,d+1);}}
function jsonSpecs($:CheerioAPI,s:Record<string,string>){$('script[type="application/ld+json"],script').each((_,e)=>{let t=$(e).contents().text().trim();if(!t||t.length>1000000)return;const eq=t.indexOf('=');if(eq>=0&&t.slice(0,eq).includes('window'))t=t.slice(eq+1).replace(/;\s*$/,'');try{flatten(JSON.parse(t),s);}catch{}});}
function extractPdp(html:string,f:SearchProduct):Product{const $=load(html),s:Record<string,string>={};tableSpecs($,s);labeledSpecs($,s);colonSpecs($,s);jsonSpecs($,s);const title=clean($('meta[property="og:title"]').attr('content')||$('h1').first().text()||f.title);let finalPrice:number|undefined;for(const c of [$('meta[property="product:price:amount"]').attr('content'),$('meta[itemprop="price"]').attr('content'),$('[class*="pdp-price" i]').first().text(),$('[class*="price" i]').first().text()]){const n=parsePriceText(c);if(n&&n>0){finalPrice=n;break;}}let originalPrice:number|undefined;for(const c of [$('meta[itemprop="highPrice"]').attr('content'),$('del').first().text(),$('[class*="origin-price" i]').first().text(),$('[class*="original-price" i]').first().text()]){const n=parsePriceText(c);if(n&&n>0){originalPrice=n;break;}}const seller=clean($('[class*="seller-name" i] a').first().text()||$('[class*="seller" i] a').first().text())||undefined;const brand=s.Brand||s.brand||clean($('[itemprop="brand"]').first().text())||undefined;const image=$('meta[property="og:image"]').attr('content')||f.image;const rt=$('body').text().match(/([\d,]+)\s*(?:ratings|reviews)/i)?.[1];const reviewCount=rt?Number(rt.replace(/,/g,'')):undefined;return{...f,title,price:finalPrice??f.price,originalPrice,image,seller,brand,reviewCount,specifications:s};}
async function extractAllSitemapProductUrls(){const root=await httpGet(PRODUCT_SITEMAP,60000);if(root.status>=400)throw new Error(`Product sitemap HTTP ${root.status}`);const children=xmlLocs(root.html);console.log(`PRODUCT SITEMAP INDEX | locs=${children.length}`);const sitemapUrls=children.filter(u=>/\.xml(?:\.gz)?(?:$|\?)/i.test(u)||/sitemap/i.test(u));const urls=new Set<string>();for(let i=0;i<sitemapUrls.length;i+=8){const batch=sitemapUrls.slice(i,i+8);const rs=await Promise.all(batch.map(async u=>{try{const r=await httpGet(u,60000);if(r.status>=400)throw new Error(`HTTP ${r.status}`);return xmlLocs(r.html).filter(isProductUrl).map(normalizeUrl);}catch(e){console.error(`PRODUCT SITEMAP FAILED ${u}:`,e instanceof Error?e.message:String(e));return[];}}));for(const arr of rs)for(const u of arr)urls.add(u);console.log(`PRODUCT SITEMAP PROGRESS ${Math.min(i+8,sitemapUrls.length)}/${sitemapUrls.length} | urls=${urls.size}`);}console.log(`PRODUCT SITEMAP COMPLETE | urls=${urls.size}`);return[...urls];}
async function saveToSupabase(p:Product,category:string,supabase:ReturnType<typeof createClient>){const{data:row,error:e1}=await supabase.from('products').upsert({title:p.title,price:p.price,currency:'NPR',image:p.image||null,link:p.url,reviews:p.reviewCount??null,rating:p.rating??null,search_term:category,website:'Daraz Nepal',marketplace_id:DARAZ_MARKETPLACE_ID,external_id:p.itemId},{onConflict:'marketplace_id,external_id'}).select('id').single();if(e1||!row?.id)throw new Error(`products upsert failed: ${e1?.message||'missing id'}`);const productId=row.id as string;const{error:e2}=await supabase.from('price_history').insert({product_id:productId,price:p.price,currency:'NPR',captured_at:new Date().toISOString()});if(e2)throw new Error(`price_history failed: ${e2.message}`);const{error:e3}=await supabase.from('product_enrichment_queue').upsert({product_id:productId,brand:p.brand||null,model:p.specifications.Model||p.specifications['Model Name']||null,product_type:category,parse_status:'needs_review',reason:'Daraz HTTP PDP collector',specifications:p.specifications,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(e3)throw new Error(`enrichment failed: ${e3.message}`);console.log(`SUPABASE SAVED | ${p.itemId} | NPR ${p.price} | specs=${Object.keys(p.specifications).length}`);}
async function main(){await Actor.init();if(!SUPABASE_SERVICE_ROLE_KEY)throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY environment variable');const supabase=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});const input=(await Actor.getInput()||{}) as any;const category=String(input.category||'smartphone').trim().toLowerCase();if(!CATEGORIES[category])throw new Error(`Invalid category: ${category}`);const minPrice=Math.max(0,Number(input.minPrice??5000));const maxProducts=Math.max(1,Number(input.maxProducts||120));const pdpConcurrency=Math.max(1,Math.min(30,Number(input.pdpConcurrency||6)));const maxRunSeconds=Math.max(60,Number(input.maxRunSeconds||900));const started=Date.now();console.log(`DARAZ HTTP-ONLY PRODUCT SITEMAP | category=${category} | PRICE-ONLY FILTER | minPrice=NPR ${minPrice} | target=${maxProducts} | runtime=${maxRunSeconds}s | pdpConcurrency=${pdpConcurrency}`);const allUrls=await extractAllSitemapProductUrls();console.log(`PRODUCT CANDIDATES | total=${allUrls.length} | category matching=DISABLED | filter=price>=NPR ${minPrice}`);let saved=0,scanned=0,failed=0;for(let i=0;i<allUrls.length&&saved<maxProducts&&(Date.now()-started)<maxRunSeconds*1000;i+=pdpConcurrency){const batch=allUrls.slice(i,i+pdpConcurrency);const results=await Promise.all(batch.map(async u=>{try{const id=itemId(u);const f:SearchProduct={title:'',url:u,itemId:id,price:0};const r=await httpGet(u,30000);if(r.status>=400)throw new Error(`HTTP ${r.status}`);if(blocked(r.html))throw new Error('Daraz CAPTCHA/block detected on PDP');const p=extractPdp(r.html,f);if(!p.price||p.price<minPrice)return{p:null,reason:'price'};if(!p.title)return{p:null,reason:'title'};return{p};}catch(e){console.error(`PDP FAILED ${u}:`,e instanceof Error?e.message:String(e));return{p:null,reason:'error'};}}));scanned+=batch.length;for(const r of results){if(!r.p){failed++;continue;}try{await saveToSupabase(r.p,category,supabase);await Actor.pushData({...r.p,category,marketplace:'Daraz Nepal',capturedAt:new Date().toISOString()});saved++;}catch(e){failed++;console.error(`SAVE FAILED ${r.p.itemId}:`,e instanceof Error?e.message:String(e));}if(saved>=maxProducts)break;}console.log(`PDP PROGRESS | scanned=${scanned} | saved=${saved} | failed=${failed} | remaining=${Math.max(0,maxProducts-saved)}`);}console.log(`COMPLETE | category=${category} sitemapUrls=${allUrls.length} | categoryMatching=DISABLED | priceOnly=true | scanned=${scanned} saved=${saved} failed=${failed}`);await Actor.exit();}
main().catch(async e=>{console.error('FATAL',e);try{await Actor.exit();}catch{}process.exit(1);});