import { Actor } from 'apify';
import { createClient } from '@supabase/supabase-js';
import { load } from 'cheerio';

const BASE='https://www.daraz.com.np';
const MARKET='6a4f8822-e1bc-4e8b-be61-4d1a400f3c13';
const SUPABASE_URL=process.env.SUPABASE_URL||'https://foupthwcnnskqlzhoyep.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const CATEGORIES=['smartphone','tablet','laptop','desktop computer','printer','camera','smart tv','computer monitor','refrigerator','washing machine','air conditioner','dishwasher'];

type SP={title:string;url:string;itemId:string;price:number;image?:string;raw?:any};
type Product=SP&{brand?:string;reviewCount?:number;rating?:number;specifications:Record<string,string>};

const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim();
const num=(v:unknown)=>{const m=String(v??'').replace(/,/g,'').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):undefined;};
const parsePrice=(v:unknown)=>{const m=clean(v).match(/(?:Rs\.?|NPR)\s*[\d,]+(?:\.\d+)?/i);return num(m?.[0]??v);};
function normalize(v:string){let x=String(v||'').replace(/\\\//g,'/').replace(/\\u002F/gi,'/').replace(/&amp;/gi,'&').trim();if(x.startsWith('//'))x='https:'+x;try{const u=new URL(x,BASE);return u.hostname.endsWith('daraz.com.np')?`${BASE}${u.pathname}`:x;}catch{return x;}}
function idOf(url:string){return url.match(/(?:\/i|\/products\/[^?#]*?-i)(\d+)(?:-s\d+)?\.html/i)?.[1]||url;}
function productUrl(v:string){return /\/(?:i\d+(?:-s\d+)?|products\/[^?#]*-i\d+(?:-s\d+)?)\.html(?:$|[?#])/i.test(v);}
async function get(url:string,extra:Record<string,string>={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),30000);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36','Accept':'application/json,text/html,application/xhtml+xml;q=0.9,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9','Cache-Control':'no-cache','Referer':`${BASE}/`,...extra}});return{status:r.status,type:r.headers.get('content-type')||'',html:await r.text()};}finally{clearTimeout(tm);}}
function decodeHtml(s:string){return s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\\u0026/g,'&').replace(/\\u003d/g,'=').replace(/\\u002F/gi,'/');}
function pushJsonCandidate(out:any[],text:string){const source=decodeHtml(text.trim());try{out.push(JSON.parse(source));return;}catch{}for(const start of [source.indexOf('{'),source.indexOf('[')]){if(start<0)continue;const open=source[start],close=open==='{'?'}':']';let depth=0,quote=false,escaped=false;for(let i=start;i<source.length;i++){const ch=source[i];if(quote){if(escaped)escaped=false;else if(ch==='\\')escaped=true;else if(ch==='"')quote=false;continue;}if(ch==='"'){quote=true;continue;}if(ch===open)depth++;else if(ch===close&&--depth===0){try{out.push(JSON.parse(source.slice(start,i+1)));}catch{}break;}}}}
function addPair(specs:Record<string,unknown>,key:unknown,value:unknown){const k=clean(String(key??''));const v=typeof value==='string'?clean(value):value;if(k&&v!==''&&v!=null&&k.length<=200)specs[k]=v;}
function extractSpecPairs(value:unknown,specs:Record<string,unknown>,context=''):void{if(value==null)return;if(Array.isArray(value)){value.forEach(v=>extractSpecPairs(v,specs,context));return;}if(typeof value!=='object')return;const obj=value as Record<string,unknown>;const key=obj.name??obj.key??obj.attributeName??obj.propertyName??obj.specName??obj.label??obj.attribute_name??obj.property_name;const val=obj.value??obj.attributeValue??obj.propertyValue??obj.specValue??obj.text??obj.displayValue??obj.display_value;if(key!=null&&val!=null&&typeof val!=='object')addPair(specs,key,val);const container=/spec|attribute|property|feature|detail|parameter|option|configuration|productoption/i.test(context);for(const[k,v]of Object.entries(obj)){if(v==null)continue;if(typeof v==='object'){if(/spec|attribute|property|feature|detail|parameter|option|configuration|sku|productOption|properties|attributes/i.test(k)||container)extractSpecPairs(v,specs,k);continue;}if(container)addPair(specs,k,v);}}
function extractSearchObjects(html:string):any[]{const out:any[]=[];try{const j=JSON.parse(html);out.push(j);}catch{}const scripts=html.match(/<script[^>]*>[\s\S]*?<\/script>/gi)||[];for(const block of scripts){const body=decodeHtml(block.replace(/^<script[^>]*>|<\/script>$/gi,'').trim());if(/itemId|productId|skuId|attributes|properties|specification|productOption|requestParams/i.test(body))pushJsonCandidate(out,body);}return out;}
function extractSpecsFromSearch(raw:any):Record<string,string>{const specs:Record<string,unknown>={};extractSpecPairs(raw,specs);const normalized:Record<string,string>={};for(const[k,v]of Object.entries(specs)){const ck=clean(k),cv=clean(String(v));if(!ck||!cv)continue;const ex=Object.keys(normalized).find(x=>x.toLowerCase()===ck.toLowerCase());if(!ex)normalized[ck]=cv;else if(cv.length>normalized[ex].length)normalized[ex]=cv;}return normalized;}
function add(out:Map<string,SP>,raw:unknown,title?:unknown,image?:unknown,p?:unknown,rawObj?:any){const u=normalize(String(raw||''));if(!productUrl(u)||out.has(u))return;out.set(u,{title:clean(title),url:u,itemId:idOf(u),price:parsePrice(p)??0,image:clean(image)||undefined,raw:rawObj});}
function addId(out:Map<string,SP>,v:unknown,title?:unknown,image?:unknown,p?:unknown,rawObj?:any){const n=String(v??'').match(/\d{6,}/)?.[0];if(n)add(out,`${BASE}/i${n}.html`,title,image,p,rawObj);}
function searchProducts(html:string){const out=new Map<string,SP>();let root:any;try{root=JSON.parse(html);}catch{root=null;}const objects:any[]=[];if(root)objects.push(root);const items=root?.mods?.listItems||root?.data?.mods?.listItems||root?.data?.items||root?.items||[];if(Array.isArray(items))for(const it of items){add(out,it?.productUrl||it?.itemUrl||it?.url,it?.name||it?.title,it?.image||it?.imageUrl||it?.images?.[0],it?.priceShow||it?.price,it);addId(out,it?.itemId||it?.item_id||it?.productId,it?.name||it?.title,it?.image||it?.imageUrl,it?.priceShow||it?.price,it);}const $=load(html);$('a[href]').each((_,a)=>add(out,$(a).attr('href'),$(a).attr('title')||$(a).text(),$(a).find('img').attr('src')||$(a).find('img').attr('data-src')));const raw=decodeHtml(html);for(const m of raw.matchAll(/(?:https?:)?\/\/(?:www\.)?daraz\.com\.np\/(?:i\d+(?:-s\d+)?|products\/[^?#]*-i\d+)\.html(?:[?#][^"'<>\s\\]*)?/gi))add(out,m[0]);for(const m of raw.matchAll(/(?:["']?(?:itemId|item_id|productId|product_id)["']?\s*[:=]\s*["']?)(\d{6,})/gi))addId(out,m[1]);return[...out.values()];}
function productFromSearch(c:SP,html:string):Product{const objects=extractSearchObjects(html);let raw=c.raw||{};if(objects.length)raw=objects[0];const specs=extractSpecsFromSearch(raw);const title=clean(c.title)||clean(raw?.name||raw?.title);const brand=clean(raw?.brandName||raw?.brand||raw?.brand_name)||specs.Brand||undefined;const rating=num(raw?.rating||raw?.ratingScore||raw?.ratings);const reviewCount=num(raw?.reviewCount||raw?.review||raw?.reviews||raw?.reviewCountShow);const price=parsePrice(raw?.priceShow||raw?.price||raw?.salePrice||raw?.discountPrice)||c.price;return{...c,title,brand,price:price||0,rating,reviewCount,specifications:specs};}
async function collect(category:string,brand:string,pages:number){const all=new Map<string,SP>();const query=clean(`${brand} ${category}`);for(let page=1;page<=pages;page++){const r=await get(`${BASE}/catalog/?ajax=true&_keyori=ss&q=${encodeURIComponent(query)}&page=${page}`,{'X-Requested-With':'XMLHttpRequest','Sec-Fetch-Dest':'empty','Sec-Fetch-Mode':'cors','Sec-Fetch-Site':'same-origin'});const ps=searchProducts(r.html);let added=0;for(const p of ps)if(!all.has(p.url)){all.set(p.url,p);added++;}console.log(`SEARCH | query="${query}" | page=${page}/${pages} | status=${r.status} | bytes=${Buffer.byteLength(r.html)} | contentType=${r.type} | products=${ps.length} | added=${added} | total=${all.size}`);if(!ps.length&&page===1)console.log(`SEARCH EMPTY | query="${query}" | status=${r.status} | sample=${JSON.stringify(clean(load(r.html).text()).slice(0,300))}`);}return[...all.values()];}
async function save(p:Product,category:string,supabase:ReturnType<typeof createClient>){const{data:row,error:e}=await supabase.from('products').upsert({title:p.title,price:p.price,currency:'NPR',image:p.image||null,link:p.url,reviews:p.reviewCount??null,rating:p.rating??null,search_term:category,website:'Daraz Nepal',marketplace_id:MARKET,external_id:p.itemId,specifications:p.specifications},{onConflict:'marketplace_id,external_id'}).select('id').single();if(e||!row?.id)throw new Error(`products upsert failed: ${e?.message||'missing id'}`);const productId=row.id as string;const{error:e2}=await supabase.from('price_history').insert({product_id:productId,price:p.price,currency:'NPR',captured_at:new Date().toISOString()});if(e2)throw new Error(`price_history failed: ${e2.message}`);const{error:e3}=await supabase.from('product_enrichment_queue').upsert({product_id:productId,brand:p.brand||null,model:p.specifications.Model||p.specifications['Model Name']||null,product_type:category,parse_status:'needs_review',reason:'Daraz HTTP search collector',specifications:p.specifications,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(e3)throw new Error(`enrichment failed: ${e3.message}`);}
async function main(){await Actor.init();if(!KEY)throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY');const input=(await Actor.getInput())||{};const category=String(input.category||CATEGORIES[0]);const brand=String(input.brand||'Samsung');const pages=Math.max(1,Math.min(100,Number(input.maxSearchPages||input.maxPages||100)));const supabase=createClient(SUPABASE_URL,KEY);console.log(`START | brand=${brand} | category=${category} | query="${clean(`${brand} ${category}`)}" | pages=${pages} | price_min=5000 | PDP=false`);const candidates=await collect(category,brand,pages);console.log(`CANDIDATES | ${candidates.length}`);let saved=0,skipped=0;for(const c of candidates){if(c.price>0&&c.price<5000){skipped++;continue;}try{const p=productFromSearch(c,'');if(!p.price||p.price<5000){skipped++;console.log(`SKIP PRICE | ${p.itemId} | ${p.price}`);continue;}await save(p,category,supabase);await Actor.pushData(p);saved++;}catch(e){console.log(`SAVE ERROR | ${c.itemId} | ${e instanceof Error?e.message:String(e)}`);}}console.log(`DONE | candidates=${candidates.length} | saved=${saved} | skipped=${skipped} | PDP_FETCHES=0`);await Actor.exit();}
main().catch(async e=>{console.error(e);try{await Actor.fail();}catch{}});
