import { Actor } from 'apify';
import { createClient } from '@supabase/supabase-js';
import { load, type CheerioAPI } from 'cheerio';

const BASE='https://www.daraz.com.np';
const MARKET='6a4f8822-e1bc-4e8b-be61-4d1a400f3c13';
const SUPABASE_URL=process.env.SUPABASE_URL||'https://foupthwcnnskqlzhoyep.supabase.co';
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const CATEGORIES=['smartphone','tablet','laptop','desktop computer','printer','camera','smart tv','computer monitor','refrigerator','washing machine','air conditioner','dishwasher'];

type SP={title:string;url:string;itemId:string;price:number;image?:string};
type Product=SP&{brand?:string;reviewCount?:number;specifications:Record<string,string>};

const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim();
const num=(v:unknown)=>{const m=String(v??'').replace(/,/g,'').match(/\d+(?:\.\d+)?/);return m?Number(m[0]):undefined;};
const parsePrice=(v:unknown)=>{const m=clean(v).match(/(?:Rs\.?|NPR)\s*[\d,]+(?:\.\d+)?/i);return num(m?.[0]??v);};
function normalize(v:string){let x=String(v||'').replace(/\\\//g,'/').replace(/\\u002F/gi,'/').replace(/&amp;/gi,'&').trim();if(x.startsWith('//'))x='https:'+x;try{const u=new URL(x,BASE);return u.hostname.endsWith('daraz.com.np')?`${BASE}${u.pathname}`:x;}catch{return x;}}
function idOf(url:string){return url.match(/(?:\/i|\/products\/[^?#]*?-i)(\d+)(?:-s\d+)?\.html/i)?.[1]||url;}
function productUrl(v:string){return /\/(?:i\d+(?:-s\d+)?|products\/[^?#]*-i\d+(?:-s\d+)?)\.html(?:$|[?#])/i.test(v);}
function blocked(html:string){const $=load(html);const t=`${clean($('title').text())} ${clean($('body').text())}`.toLowerCase();return ['verify you are human','are you a robot','unusual traffic','access denied','robot check','captcha verification failed','security check required'].some(x=>t.includes(x));}
async function get(url:string,extra:Record<string,string>={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),30000);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36','Accept':'application/json,text/html,application/xhtml+xml;q=0.9,*/*;q=0.8','Accept-Language':'en-US,en;q=0.9','Cache-Control':'no-cache','Referer':`${BASE}/`,...extra}});return{status:r.status,type:r.headers.get('content-type')||'',html:await r.text()};}finally{clearTimeout(tm);}}

function addSpec(s:Record<string,string>,k:unknown,v:unknown){const a=clean(k),b=clean(v);if(!a||!b||a.length>150||b.length>2000)return;const bad=/^(?:@type|context|availability|url|image|logo|name|description|brand|price|pricecurrency|offers?|aggregateRating|ratingValue|reviewCount|sku|mpn|gtin)/i.test(a);if(bad&&/^(?:https?:\/\/|\{?https?:\/\/)/i.test(b))return;if(!s[a])s[a]=b;}
function tableSpecs($:CheerioAPI,s:Record<string,string>){$('table tr').each((_,r)=>{const c=$(r).find('th,td').map((_,e)=>clean($(e).text())).get().filter(Boolean);if(c.length>=2)addSpec(s,c[0],c.slice(1).join(' | '));});}
function labeledSpecs($:CheerioAPI,s:Record<string,string>){
  const pairSelectors=[
    '.specification-attribute',
    '.specification-attribute-item',
    '[class*="specification-attribute" i]',
    '[class*="specification-attribute-item" i]',
    '[class*="key-value" i]',
    '[class*="product-property" i]',
    '[class*="product-attribute" i]'
  ];
  $(pairSelectors.join(',')).each((_,b)=>{
    const el=$(b);
    const key=el.find('.specification-attribute-name,[class*="specification-attribute-name" i],[class*="attribute-name" i],[class*="key" i],[class*="name" i]').first().text();
    const val=el.find('.specification-attribute-value,[class*="specification-attribute-value" i],[class*="attribute-value" i],[class*="value" i],[class*="val" i]').first().text();
    if(clean(key)&&clean(val)){addSpec(s,key,val);return;}
    const children=el.children().map((_,e)=>clean($(e).text())).get().filter(Boolean);
    if(children.length>=2){addSpec(s,children[0],children.slice(1).join(' | '));return;}
    const t=clean(el.text()),i=t.indexOf(':');if(i>1&&i<150)addSpec(s,t.slice(0,i),t.slice(i+1));
  });
  $('[class*="specification" i],[class*="specs" i],[class*="attribute" i],[class*="product-property" i]').each((_,b)=>{$(b).find('li,tr,p,dt,dd').each((_,r)=>{const c=$(r).children().map((_,e)=>clean($(e).text())).get().filter(Boolean);if(c.length>=2)addSpec(s,c[0],c.slice(1).join(' | '));else{const t=clean($(r).text()),i=t.indexOf(':');if(i>1&&i<150)addSpec(s,t.slice(0,i),t.slice(i+1));}});});
}
function colonSpecs($:CheerioAPI,s:Record<string,string>){$('li,p,dt,dd').each((_,e)=>{const t=clean($(e).text()),i=t.indexOf(':');if(t.length<=600&&i>1&&i<120)addSpec(s,t.slice(0,i),t.slice(i+1));});}
function flatten(v:unknown,s:Record<string,string>,d=0){if(d>8||v==null)return;if(Array.isArray(v)){for(const x of v)flatten(x,s,d+1);return;}if(typeof v!=='object')return;for(const[k,x]of Object.entries(v as Record<string,unknown>)){const n=k.toLowerCase().replace(/[^a-z0-9]/g,'');if(['specifications','specification','attributes','attribute','productattributes','productspecifications','properties','productproperty','skuattributes','itemproperties','itemattributes'].includes(n)){flatten(x,s,d+1);continue;}if(['string','number','boolean'].includes(typeof x)){if(d>=1)addSpec(s,k,x);}else if(d<5)flatten(x,s,d+1);}}
function jsonSpecs($:CheerioAPI,s:Record<string,string>){$('script').each((_,e)=>{let t=$(e).contents().text().trim();if(!t||t.length>1500000)return;t=t.replace(/\\u002F/gi,'/').replace(/\\\//g,'/');try{const v=JSON.parse(t);if(v&&typeof v==='object'&&!Array.isArray(v)){const typ=clean((v as any)['@type']).toLowerCase();if(['brand','productgroup','offer','aggregateoffer'].includes(typ))return;flatten(v,s);}}catch{const m=t.match(/(?:window\.[A-Za-z0-9_$]+|globalThis\.[A-Za-z0-9_$]+|var\s+[A-Za-z0-9_$]+)\s*=\s*(\{[\s\S]*\}|\[[\s\S]*\])\s*;?\s*$/);if(m){try{flatten(JSON.parse(m[1]),s);}catch{}}}});}
function textSpecs(html:string,s:Record<string,string>){const x=html.replace(/\\u002F/gi,'/').replace(/\\\//g,'/').replace(/&quot;/gi,'"').replace(/&#34;/gi,'"');const patterns=[/"name"\s*:\s*"([^"\\\n]{2,120})"\s*,\s*"value"\s*:\s*"([^"\\\n]{1,500})"/gi,/"(?:key|label)"\s*:\s*"([^"\\\n]{2,120})"\s*,\s*"(?:value|text)"\s*:\s*"([^"\\\n]{1,500})"/gi,/"(?:attributeName|propertyName)"\s*:\s*"([^"\\\n]{2,120})"\s*,\s*"(?:attributeValue|propertyValue)"\s*:\s*"([^"\\\n]{1,500})"/gi];for(const re of patterns)for(const m of x.matchAll(re))addSpec(s,m[1],m[2]);}
function targetedDarazText(html:string,s:Record<string,string>){
  const x=html.replace(/\\u002F/gi,'/').replace(/\\\//g,'/').replace(/&quot;/gi,'"').replace(/&#34;/gi,'"');
  const sections=[...x.matchAll(/(?:specification|specifications|productSpec|productSpecification|productAttributes|attributes)[^\{]{0,300}(\{[\s\S]{0,50000}\})/gi)];
  for(const m of sections){try{const cleaned=m[1].replace(/,\s*([}\]])/g,'$1');flatten(JSON.parse(cleaned),s);}catch{}}
  const escapedPairs=/(?:specification-attribute-name|attributeName|propertyName)[^>]{0,500}?>([^<]{2,150})<[^>]*>[\s\S]{0,500}?(?:specification-attribute-value|attributeValue|propertyValue)[^>]*>([^<]{1,1000})</gi;
  for(const m of x.matchAll(escapedPairs))addSpec(s,m[1],m[2]);
}
function pdp(html:string,f:SP):Product{const $=load(html),s:Record<string,string>={};tableSpecs($,s);labeledSpecs($,s);colonSpecs($,s);jsonSpecs($,s);textSpecs(html,s);targetedDarazText(html,s);let p:number|undefined;for(const v of [$('meta[property="product:price:amount"]').attr('content'),$('meta[itemprop="price"]').attr('content'),$('[class*="pdp-price" i]').first().text(),$('[class*="price" i]').first().text()]){p=parsePrice(v);if(p&&p>0)break;}const brand=clean($('[itemprop="brand"]').first().text())||s.Brand||s.brand||undefined;const rt=$('body').text().match(/([\d,]+)\s*(?:ratings|reviews)/i)?.[1];return{...f,title:clean($('meta[property="og:title"]').attr('content')||$('h1').first().text()||f.title),price:p??f.price,image:$('meta[property="og:image"]').attr('content')||f.image,brand,reviewCount:rt?Number(rt.replace(/,/g,'')):undefined,specifications:s};}
function add(out:Map<string,SP>,raw:unknown,title?:unknown,image?:unknown,p?:unknown){const u=normalize(String(raw||''));if(!productUrl(u)||out.has(u))return;out.set(u,{title:clean(title),url:u,itemId:idOf(u),price:parsePrice(p)??0,image:clean(image)||undefined});}
function addId(out:Map<string,SP>,v:unknown,title?:unknown,image?:unknown,p?:unknown){const n=String(v??'').match(/\d{6,}/)?.[0];if(n)add(out,`${BASE}/i${n}.html`,title,image,p);}
function searchProducts(html:string){const $=load(html),out=new Map<string,SP>();try{const j=JSON.parse(html),items=j?.mods?.listItems||j?.data?.mods?.listItems||j?.data?.items||j?.items||[];if(Array.isArray(items))for(const it of items){add(out,it?.productUrl||it?.itemUrl||it?.url,it?.name||it?.title,it?.image||it?.imageUrl||it?.images?.[0],it?.priceShow||it?.price);addId(out,it?.itemId||it?.item_id||it?.productId,it?.name||it?.title,it?.image||it?.imageUrl,it?.priceShow||it?.price);}}catch{}$('a[href]').each((_,a)=>add(out,$(a).attr('href'),$(a).attr('title')||$(a).text(),$(a).find('img').attr('src')||$(a).find('img').attr('data-src')));const raw=html.replace(/\\u002F/gi,'/').replace(/\\\//g,'/');for(const m of raw.matchAll(/(?:https?:)?\/\/(?:www\.)?daraz\.com\.np\/(?:i\d+(?:-s\d+)?|products\/[^?#]*-i\d+)\.html(?:[?#][^"'<>\s\\]*)?/gi))add(out,m[0]);for(const m of raw.matchAll(/(?:["']?(?:itemId|item_id|productId|product_id)["']?\s*[:=]\s*["']?)(\d{6,})/gi))addId(out,m[1]);return[...out.values()];}

async function collect(category:string,pages:number){const all=new Map<string,SP>();for(let page=1;page<=pages;page++){let mode='ajax';let r=await get(`${BASE}/catalog/?ajax=true&_keyori=ss&q=${encodeURIComponent(category)}&page=${page}`,{'X-Requested-With':'XMLHttpRequest','Sec-Fetch-Dest':'empty','Sec-Fetch-Mode':'cors','Sec-Fetch-Site':'same-origin'});let ps=searchProducts(r.html);if(!ps.length){mode='catalog';r=await get(`${BASE}/catalog/?q=${encodeURIComponent(category)}&page=${page}`,{'Sec-Fetch-Dest':'document','Sec-Fetch-Mode':'navigate','Sec-Fetch-Site':'same-origin'});ps=searchProducts(r.html);}let added=0;for(const p of ps)if(!all.has(p.url)){all.set(p.url,p);added++;}console.log(`SEARCH PAGE ${page}/${pages} | mode=${mode} | status=${r.status} | bytes=${Buffer.byteLength(r.html)} | contentType=${r.type} | products=${ps.length} | added=${added} | total=${all.size}`);if(!ps.length){console.log(`SEARCH EMPTY | mode=${mode} | blocked=${blocked(r.html)} | sample=${JSON.stringify(clean(load(r.html).text()).slice(0,300))}`);}}return[...all.values()];}

async function save(p:Product,category:string,supabase:ReturnType<typeof createClient>){const{data:row,error:e}=await supabase.from('products').upsert({title:p.title,price:p.price,currency:'NPR',image:p.image||null,link:p.url,reviews:p.reviewCount??null,rating:null,search_term:category,website:'Daraz Nepal',marketplace_id:MARKET,external_id:p.itemId,specifications:p.specifications},{onConflict:'marketplace_id,external_id'}).select('id').single();if(e||!row?.id)throw new Error(`products upsert failed: ${e?.message||'missing id'}`);const productId=row.id as string;const{error:e2}=await supabase.from('price_history').insert({product_id:productId,price:p.price,currency:'NPR',captured_at:new Date().toISOString()});if(e2)throw new Error(`price_history failed: ${e2.message}`);const{error:e3}=await supabase.from('product_enrichment_queue').upsert({product_id:productId,brand:p.brand||null,model:p.specifications.Model||p.specifications['Model Name']||null,product_type:category,parse_status:'needs_review',reason:'Daraz HTTP PDP collector',specifications:p.specifications,updated_at:new Date().toISOString()},{onConflict:'product_id'});if(e3)throw new Error(`enrichment failed: ${e3.message}`);console.log(`SUPABASE SAVED | ${p.itemId} | NPR ${p.price} | specs=${Object.keys(p.specifications).length}`);}

async function main(){await Actor.init();if(!KEY)throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY environment variable');const supabase=createClient(SUPABASE_URL,KEY,{auth:{autoRefreshToken:false,persistSession:false}});const input=(await Actor.getInput()||{}) as any;const category=String(input.category||'smartphone').trim().toLowerCase();if(!CATEGORIES.includes(category))throw new Error(`Invalid category: ${category}`);const minPrice=Math.max(0,Number(input.minPrice??5000));const pages=Math.max(1,Math.min(100,Number(input.maxSearchPages||100)));const concurrency=Math.max(1,Math.min(30,Number(input.pdpConcurrency||6)));const runtime=Math.max(60,Number(input.maxRunSeconds||900));const started=Date.now();console.log(`DARAZ HTTP-ONLY SEARCH | category=${category} | AJAX+CATALOG FALLBACK | searchPages=${pages} | NO PRODUCT LIMIT | PRICE-ONLY FILTER | minPrice=NPR ${minPrice} | runtime=${runtime}s | pdpConcurrency=${concurrency}`);const candidates=await collect(category,pages);console.log(`PRODUCT CANDIDATES | total=${candidates.length} | category matching=DISABLED | filter=price>=NPR ${minPrice}`);let scanned=0,saved=0,failed=0;for(let i=0;i<candidates.length&&(Date.now()-started)<runtime*1000;i+=concurrency){const batch=candidates.slice(i,i+concurrency);const rs=await Promise.all(batch.map(async f=>{try{const r=await get(f.url);if(r.status>=400)throw new Error(`HTTP ${r.status}`);if(blocked(r.html))throw new Error('Daraz block detected');const p=pdp(r.html,f);if(!p.price||p.price<minPrice)return null;if(!p.title)return null;return p;}catch(e){console.error(`PDP FAILED ${f.url}:`,e instanceof Error?e.message:String(e));return null;}}));scanned+=batch.length;for(const p of rs){if(!p){failed++;continue;}try{await save(p,category,supabase);await Actor.pushData({...p,category,marketplace:'Daraz Nepal',capturedAt:new Date().toISOString()});saved++;}catch(e){failed++;console.error(`SAVE FAILED:`,e instanceof Error?e.message:String(e));}}console.log(`PDP PROGRESS | scanned=${scanned} | saved=${saved} | failed=${failed}`);}console.log(`COMPLETE | category=${category} | candidates=${candidates.length} | scanned=${scanned} | saved=${saved} | failed=${failed}`);await Actor.exit();}
main().catch(async e=>{console.error('FATAL',e);try{await Actor.exit();}catch{}process.exit(1);});